### ISSUE TITLE
Grouped section with header and footer text

### ISSUE THREAD

**Issue by m5o** [SimpleBoilerplates/SwiftUI-Cheat-Sheet#20]
Apple is using the grouped sections a lot in their iOS setting app. Do the sections also provide a footer parameter?

In most of The iOS Interface the header text is uppercase and the footer small and gray-ish. Will this be handled by SwiftUI in the future?

Thank you for building this reference!

**Comment by iNoles** [comment]
Section(header=Text("Header"), footer=Text("Footer")

**Comment by m5o** [comment]
Thank you @iNoles
It would be nice if this could be added to the cheat sheet including a screenshot.

**Comment by Sadmansamee** [comment]
@iNoles @m5o why not make PR for this!

**Comment by maeganjwilson** [comment]
@Sadmansamee I'm trying to make an example for this, but are there any tips on how to get the screenshots? Or should I just submit a PR for the code and someone else can do the screenshot
