### ISSUE TITLE
"To add a footer to a section" contains wrong screenshot

### ISSUE THREAD

**Issue by w-i-n-s** [SimpleBoilerplates/SwiftUI-Cheat-Sheet#26]
Actually it follow to wrong link without footers

![wrong link](https://github.com/SimpleBoilerplates/SwiftUI-Cheat-Sheet/blob/master/assets/images/list/3.png)

**Comment by Sadmansamee** [comment]
would you like to create a pull request with the fix?

**Comment by w-i-n-s** [comment]
> would you like to create a pull request with the fix?

Unfortunately, ATM I busy on SwiftUI project. Will do it when I'll have some free time.
