### ISSUE TITLE
UIVisualEffectView Equivalent?

### ISSUE THREAD

**Issue by sebj** [SimpleBoilerplates/SwiftUI-Cheat-Sheet#9]
I'm interested to know whether there's a SwiftUI equivalent for UIVisualEffectView (or an equivalent for UIBlurEffect..)

**Comment by Sadmansamee** [comment]
I didn't find any yet, still you could use UIVisualEffectView or UIBlurEffect inside SwiftUI without any problem.

**Comment by sebj** [comment]
This repo's now very out of date, but as I'm tidying up my Github issues – this is now covered by 'materials' in SwiftUI 3 from iOS 15+ (https://developer.apple.com/documentation/swiftui/material)
